/**
 * Build script to combine modular files from src/js/ into homepage_animations.js
 */

const fs = require('fs');
const path = require('path');

// Output file
const outputFile = path.join(__dirname, 'homepage_animations.js');

// Function to remove module.exports and clean up the code
function cleanModuleCode(content) {
  // Remove module.exports blocks (multi-line)
  content = content.replace(/\/\/ Export functions for use in main file[\s\S]*?if \(typeof module !== 'undefined' && module\.exports\) \{[\s\S]*?\}\n?/g, '');
  
  // Remove extra blank lines
  content = content.replace(/\n{3,}/g, '\n\n');
  
  return content.trim();
}

// Function to build the main file
function build() {
  console.log('Building homepage_animations.js from src/js/ modules...\n');
  
  let output = '';
  
  // Header
  output += '/**\n';
  output += ' * Balnova Homepage Animations\n';
  output += ' * Main animation file for homepage interactions\n';
  output += ' * This file is auto-generated from src/js/ modules\n';
  output += ' * DO NOT EDIT THIS FILE DIRECTLY - Edit files in src/js/ instead\n';
  output += ' * Run \'npm run build\' to regenerate this file\n';
  output += ' */\n\n';
  
  // ===== HERO SECTION =====
  output += '// ============================================================================\n';
  output += '// HERO SECTION ANIMATIONS\n';
  output += '// ============================================================================\n\n';
  
  let heroContent = fs.readFileSync(path.join(__dirname, 'src/js/hero-animations.js'), 'utf8');
  heroContent = cleanModuleCode(heroContent);
  
  // Extract the initHeroAnimations function body
  const initHeroMatch = heroContent.match(/function initHeroAnimations\(\) \{([\s\S]*?)\n\}/);
  
  // Find the start of the initHeroAnimations function (including its comment)
  // Look for the comment that precedes it
  const commentStart = heroContent.lastIndexOf('/**', heroContent.indexOf('function initHeroAnimations()'));
  const funcStart = heroContent.indexOf('function initHeroAnimations()');
  
  if (funcStart === -1) {
    // Function not found, output everything
    output += heroContent.trim() + '\n\n';
  } else {
    // Get everything before the comment (if found) or before the function
    const cutPoint = (commentStart > 0 && commentStart < funcStart) ? commentStart : funcStart;
    let heroCode = heroContent.substring(0, cutPoint);
    heroCode = heroCode.trim();
    output += heroCode + '\n\n';
  }
  
  // Add initHeroAnimations code inline (without the function wrapper)
  if (initHeroMatch) {
    output += '// Initialize hero animations on page load\n';
    output += '// Wait for DOM to be ready\n';
    output += '(function initHeroOnLoad() {\n';
    output += '  function initHeroAnimations() {\n';
    // Indent the function body
    let heroBody = initHeroMatch[1].trim();
    heroBody = heroBody.split('\n').map(line => '    ' + line).join('\n');
    output += heroBody;
    output += '\n  }\n';
    output += '  \n';
    output += '  if (document.readyState === \'loading\') {\n';
    output += '    document.addEventListener(\'DOMContentLoaded\', function() {\n';
    output += '      setTimeout(initHeroAnimations, 100);\n';
    output += '    });\n';
    output += '  } else {\n';
    output += '    setTimeout(initHeroAnimations, 100);\n';
    output += '  }\n';
    output += '})();\n\n';
  }
  
  // ===== RIPPLE EFFECT =====
  output += '// ============================================================================\n';
  output += '// RIPPLE EFFECT INITIALIZATION\n';
  output += '// ============================================================================\n\n';
  
  let rippleContent = fs.readFileSync(path.join(__dirname, 'src/js/ripple-effect.js'), 'utf8');
  rippleContent = cleanModuleCode(rippleContent);
  
  // Extract initRippleEffect function body
  const rippleMatch = rippleContent.match(/function initRippleEffect\(\) \{([\s\S]*?)\n\}/);
  if (rippleMatch) {
    // Get the function body content
    let rippleBody = rippleMatch[1];
    // Add safety checks for jQuery and ripple element
    output += 'function initRippleEffect() {\n';
    output += '  // Check if jQuery and ripple plugin are loaded\n';
    output += '  if (typeof $ === \'undefined\' || typeof $.fn.ripples === \'undefined\') {\n';
    output += '    console.warn(\'Balnova Animations: jQuery or ripple plugin not loaded. Ripple effect will not work.\');\n';
    output += '    return;\n';
    output += '  }\n';
    output += '  \n';
    output += '  const rippleElement = document.querySelector(\'#ripple\');\n';
    output += '  if (!rippleElement) {\n';
    output += '    console.warn(\'Balnova Animations: #ripple element not found. Ripple effect will not work.\');\n';
    output += '    return;\n';
    output += '  }\n\n';
    output += rippleBody;
    output += '  \n';
    output += '  img.onerror = () => {\n';
    output += '    console.warn(\'Balnova Animations: Ripple image failed to load.\');\n';
    output += '  };\n';
    output += '}\n\n';
  } else {
    // Fallback: if regex doesn't match, try to extract the content differently
    const altMatch = rippleContent.match(/\{([\s\S]*?)\n\}/);
    if (altMatch) {
      output += 'function initRippleEffect() {\n';
      output += '  if (typeof $ === \'undefined\' || typeof $.fn.ripples === \'undefined\') return;\n';
      output += '  const rippleElement = document.querySelector(\'#ripple\');\n';
      output += '  if (!rippleElement) return;\n';
      output += altMatch[1];
      output += '\n}\n\n';
    }
  }
  
  // ===== MAIN GSAP SETUP =====
  output += '// ============================================================================\n';
  output += '// MAIN GSAP ANIMATIONS SETUP\n';
  output += '// ============================================================================\n\n';
  
  output += '// Add startup message\n';
  output += 'console.log(\'Balnova Animations: Script loaded, waiting for DOM...\');\n\n';
  
  output += '// Function to check if GSAP and plugins are loaded\n';
  output += 'function checkGSAPDependencies() {\n';
  output += '  if (typeof gsap === \'undefined\') {\n';
  output += '    console.error(\'Balnova Animations: GSAP is not loaded. Please include GSAP library.\');\n';
  output += '    return false;\n';
  output += '  }\n';
  output += '  if (typeof ScrollTrigger === \'undefined\') {\n';
  output += '    console.error(\'Balnova Animations: ScrollTrigger plugin is not loaded.\');\n';
  output += '    return false;\n';
  output += '  }\n';
  output += '  if (typeof SplitText === \'undefined\') {\n';
  output += '    console.error(\'Balnova Animations: SplitText plugin is not loaded.\');\n';
  output += '    return false;\n';
  output += '  }\n';
  output += '  if (typeof Flip === \'undefined\') {\n';
  output += '    console.error(\'Balnova Animations: Flip plugin is not loaded.\');\n';
  output += '    return false;\n';
  output += '  }\n';
  output += '  return true;\n';
  output += '}\n\n';
  
  output += '// Function to safely set GSAP properties\n';
  output += 'function safeGSAPSet(selector, props) {\n';
  output += '  const elements = document.querySelectorAll(selector);\n';
  output += '  if (elements.length === 0) {\n';
  output += '    console.warn(\'Balnova Animations: Element not found:\', selector);\n';
  output += '    return false;\n';
  output += '  }\n';
  output += '  gsap.set(elements, props);\n';
  output += '  return true;\n';
  output += '}\n\n';
  
  output += 'document.addEventListener("DOMContentLoaded", (event) => {\n';
  output += '  console.log(\'Balnova Animations: DOM loaded, waiting for fonts...\');\n';
  output += '  \n';
  output += '  document.fonts.ready.then(() => {\n';
  output += '    console.log(\'Balnova Animations: Fonts ready, initializing...\');\n\n';
  output += '    // Check if GSAP and plugins are loaded\n';
  output += '    if (!checkGSAPDependencies()) {\n';
  output += '      console.error(\'Balnova Animations: Required dependencies not loaded. Animations will not work.\');\n';
  output += '      console.error(\'Balnova Animations: Please include GSAP and plugins before this script.\');\n';
  output += '      return;\n';
  output += '    }\n\n';
  output += '    console.log(\'Balnova Animations: All dependencies loaded ✓\');\n\n';
  output += '    // Register GSAP plugins\n';
  output += '    gsap.registerPlugin(ScrollTrigger, SplitText, Flip);\n';
  output += '    console.log(\'Balnova Animations: GSAP plugins registered ✓\');\n\n';
  output += '    // Check for critical elements\n';
  output += '    const mainWrapper = document.querySelector(".main-wrapper");\n';
  output += '    if (!mainWrapper) {\n';
  output += '      console.error(\'Balnova Animations: .main-wrapper element not found! This is required for scroll animations.\');\n';
  output += '      return;\n';
  output += '    }\n';
  output += '    console.log(\'Balnova Animations: .main-wrapper found ✓\');\n\n';
  output += '    // Initial GSAP settings - with element existence checks\n';
  output += '    const aboutSection = safeGSAPSet(".section_home-about", { position: "absolute" });\n';
  output += '    const serviceSection = safeGSAPSet(".section_home-service", { position: "absolute" });\n';
  output += '    safeGSAPSet(".home_about-text, .service_border-text, .service_button", { autoAlpha: 0 });\n';
  output += '    safeGSAPSet(".home_service-text", { autoAlpha: 0, y: 30, filter: "blur(8px)", scale: 0.85 });\n';
  output += '    safeGSAPSet(".about_image-wrapper", { y: "100%" });\n';
  output += '    safeGSAPSet(".about_design-wrapper", { x: "100%" });\n';
  output += '    \n';
  output += '    // Check if .home_about-left exists before setting\n';
  output += '    const aboutLeft = document.querySelector(".home_about-left");\n';
  output += '    if (aboutLeft) {\n';
  output += '      gsap.set(aboutLeft, { clipPath: "polygon(0 0, 0 0, 0 100%, 0% 100%)" });\n';
  output += '      console.log(\'Balnova Animations: .home_about-left found and initialized ✓\');\n';
  output += '    } else {\n';
  output += '      console.warn(\'Balnova Animations: .home_about-left element not found\');\n';
  output += '    }\n';
  output += '    \n';
  output += '    if (!aboutSection) {\n';
  output += '      console.warn(\'Balnova Animations: .section_home-about not found - about section animations may not work\');\n';
  output += '    }\n';
  output += '    if (!serviceSection) {\n';
  output += '      console.warn(\'Balnova Animations: .section_home-service not found - service section animations may not work\');\n';
  output += '    }\n\n';
  
  // ===== SERVICE SECTION =====
  output += '    // ========================================================================\n';
  output += '    // SERVICE SECTION ANIMATIONS\n';
  output += '    // ========================================================================\n\n';
  
  output += '    const serviceImages = document.querySelectorAll(".home_service-image");\n';
  output += '    const serviceTexts = document.querySelectorAll(".home_service-text");\n\n';
  output += '    gsap.set(serviceImages, { autoAlpha: 0, zIndex: 0 });\n\n';
  output += '    document.querySelectorAll(".service_button-wrapper").forEach(btn => {\n';
  output += '      gsap.set(btn, { autoAlpha: btn.getAttribute("data-text") == "1" ? 1 : 0 });\n';
  output += '    });\n\n';
  
  let serviceContent = fs.readFileSync(path.join(__dirname, 'src/js/service-reveal.js'), 'utf8');
  serviceContent = cleanModuleCode(serviceContent);
  
  // Split into lines and remove variable declarations
  let serviceLines = serviceContent.split('\n');
  let skipNextEmpty = false;
  let inVarBlock = false;
  let varBlockCount = 0;
  
  serviceLines = serviceLines.filter((line, index) => {
    const trimmed = line.trim();
    
    // Skip variable declarations
    if (trimmed.startsWith('let currentIndex') || 
        trimmed.startsWith('let isAnimating') || 
        trimmed.startsWith('let serviceRevealed') ||
        trimmed.startsWith('const clipHidden') ||
        trimmed.startsWith('const clipVisible')) {
      inVarBlock = true;
      varBlockCount++;
      return false;
    }
    
    // Skip empty line after variable block
    if (inVarBlock && trimmed === '' && varBlockCount >= 5) {
      inVarBlock = false;
      varBlockCount = 0;
      return false;
    }
    
    return true;
  });
  
  serviceContent = serviceLines.join('\n');
  
  // Modify function signatures to remove parameters
  serviceContent = serviceContent.replace(/function revealService\(index, serviceImages, serviceTexts\)/g, 'function revealService(index)');
  serviceContent = serviceContent.replace(/function resetServiceSection\(serviceImages, serviceTexts\)/g, 'function resetServiceSection()');
  serviceContent = serviceContent.replace(/function initServiceListeners\(serviceTexts, serviceImages\)/g, 'function initServiceListeners()');
  
  // Fix the revealService call in initServiceListeners
  serviceContent = serviceContent.replace(/revealService\(i, serviceImages, serviceTexts\)/g, 'revealService(i)');
  
  // Remove any leftover module.exports closing braces
  serviceContent = serviceContent.replace(/\n\/\/ Export functions for use in main file[\s\S]*?if \(typeof module !== 'undefined' && module\.exports\) \{[\s\S]*?\}\n?\}?\n?$/, '');
  
  // Add variable declarations inline
  output += '    let currentIndex = -1;\n';
  output += '    let isAnimating = false;\n';
  output += '    let serviceRevealed = false;\n\n';
  output += '    const clipHidden = "polygon(0 100%, 100% 100%, 100% 100%, 0 100%)";\n';
  output += '    const clipVisible = "polygon(0 100%, 100% 100%, 100% 0%, 0 0%)";\n\n';
  
  // Indent all lines, preserving empty lines
  serviceContent = serviceContent.split('\n').map(line => {
    if (line.trim() === '') return '';
    return '    ' + line;
  }).join('\n');
  
  // Remove any trailing module.exports remnants
  serviceContent = serviceContent.replace(/\s*\};\s*\}\s*$/, '');
  
  output += serviceContent + '\n\n';
  
  output += '    // Service text click handlers\n';
  output += '    initServiceListeners();\n\n';
  
  // ===== ABOUT SECTION =====
  output += '    // ========================================================================\n';
  output += '    // ABOUT SECTION ANIMATIONS\n';
  output += '    // ========================================================================\n\n';
  
  let aboutContent = fs.readFileSync(path.join(__dirname, 'src/js/about-section.js'), 'utf8');
  aboutContent = cleanModuleCode(aboutContent);
  
  // Debug: Check if we have content
  if (aboutContent.trim().length === 0) {
    console.error('ERROR: About section content is empty after cleanModuleCode!');
    aboutContent = fs.readFileSync(path.join(__dirname, 'src/js/about-section.js'), 'utf8');
    // Don't use cleanModuleCode if it's removing everything
  }
  
  // Remove initAboutSection function (we'll initialize split inline)
  aboutContent = aboutContent.replace(/function initAboutSection\(\) \{[\s\S]*?\n\}/, '');
  aboutContent = aboutContent.replace(/initAboutSection\(\);\n\n?/g, '');
  
  // Replace split initialization - but check if element exists first
  aboutContent = aboutContent.replace(/let split = null;/, 'let split = null;\n    const aboutTextEl = document.querySelector(".home_about-text");\n    if (aboutTextEl && typeof SplitText !== \'undefined\') {\n      split = new SplitText(".home_about-text", { type: "lines", mask: "lines" });\n    } else {\n      console.warn(\'Balnova Animations: .home_about-text element or SplitText plugin not found\');\n    }');
  
  // Keep getAboutLeftClip function - it's needed for the scroll timeline
  // Don't remove it - the regex was too aggressive
  
  // Make sure we still have content after all replacements
  if (aboutContent.trim().length === 0) {
    console.error('ERROR: About section content is empty after all processing!');
  }
  
  // Indent all lines, preserving empty lines
  aboutContent = aboutContent.split('\n').map(line => {
    if (line.trim() === '') return '';
    return '    ' + line;
  }).join('\n');
  
  // Clean up any trailing issues
  aboutContent = aboutContent.replace(/\n\s*;\s*\n\s*\}\s*$/, '');
  
  output += aboutContent + '\n\n';
  
  // ===== LOGO ANIMATIONS =====
  output += '    // ========================================================================\n';
  output += '    // LOGO ANIMATIONS\n';
  output += '    // ========================================================================\n\n';
  
  let logoContent = fs.readFileSync(path.join(__dirname, 'src/js/logo-animations.js'), 'utf8');
  logoContent = cleanModuleCode(logoContent);
  
  // Extract initLogoAnimations function body
  const logoMatch = logoContent.match(/function initLogoAnimations\(\) \{([\s\S]*?)\n\}/);
  if (logoMatch) {
    let logoCode = logoMatch[1];
    // Indent all lines
    logoCode = logoCode.split('\n').map(line => '    ' + line).join('\n');
    output += logoCode + '\n\n';
  }
  
  // ===== SCROLL TIMELINE =====
  output += '    // ========================================================================\n';
  output += '    // MAIN SCROLL TIMELINE\n';
  output += '    // ========================================================================\n\n';
  
  let scrollContent = fs.readFileSync(path.join(__dirname, 'src/js/scroll-timeline.js'), 'utf8');
  scrollContent = cleanModuleCode(scrollContent);
  
  // Extract initScrollTimeline function body
  const scrollMatch = scrollContent.match(/function initScrollTimeline\([^)]+\) \{([\s\S]*?)\n\}/);
  if (scrollMatch) {
    let scrollCode = scrollMatch[1];
    
    // Replace function parameter calls with inline variables
    scrollCode = scrollCode.replace(/getAboutLeftClip\(\)/g, 'aboutLeftClip');
    scrollCode = scrollCode.replace(/getAboutRevealed\(\)/g, 'aboutRevealed');
    scrollCode = scrollCode.replace(/getAboutExiting\(\)/g, 'aboutExiting');
    scrollCode = scrollCode.replace(/getServiceRevealed\(\)/g, 'serviceRevealed');
    scrollCode = scrollCode.replace(/revealService\(0, serviceImages, serviceTexts\)/g, 'revealService(0)');
    scrollCode = scrollCode.replace(/resetServiceSection\(serviceImages, serviceTexts\)/g, 'resetServiceSection()');
    
    // Indent all lines
    scrollCode = scrollCode.split('\n').map(line => '    ' + line).join('\n');
    output += scrollCode + '\n\n';
  }
  
  // Initialize ripple
  output += '    // Initialize ripple effect\n';
  output += '    initRippleEffect();\n';
  output += '    \n';
  output += '    // Final initialization message\n';
  output += '    console.log(\'Balnova Animations: Initialization complete! ✓\');\n';
  output += '    console.log(\'Balnova Animations: If animations are not working, check:\');\n';
  output += '    console.log(\'  1. All required HTML classes exist\');\n';
  output += '    console.log(\'  2. CSS file is loaded\');\n';
  output += '    console.log(\'  3. GSAP and plugins are loaded before this script\');\n\n';
  
  // Close DOMContentLoaded
  output += '  });\n';
  output += '});\n';
  
  // Write the file
  fs.writeFileSync(outputFile, output, 'utf8');
  
  console.log('✓ Successfully built homepage_animations.js');
  console.log('✓ Ready to use!\n');
}

// Run the build
try {
  build();
} catch (error) {
  console.error('Build failed:', error.message);
  console.error(error.stack);
  process.exit(1);
}
