/**
 * Build script to combine modular files from src/js/ into homepage_animations.js
 */

const fs = require('fs');
const path = require('path');

// Output file
const outputFile = path.join(__dirname, 'homepage_animations.js');

// Function to remove module.exports and clean up the code
function cleanModuleCode(content) {
  // Remove module.exports blocks (multi-line)
  content = content.replace(/\/\/ Export functions for use in main file[\s\S]*?if \(typeof module !== 'undefined' && module\.exports\) \{[\s\S]*?\}\n?/g, '');
  
  // Remove extra blank lines
  content = content.replace(/\n{3,}/g, '\n\n');
  
  return content.trim();
}

// Function to build the main file
function build() {
  console.log('Building homepage_animations.js from src/js/ modules...\n');
  
  let output = '';
  
  // Header
  output += '/**\n';
  output += ' * Balnova Homepage Animations\n';
  output += ' * Main animation file for homepage interactions\n';
  output += ' * This file is auto-generated from src/js/ modules\n';
  output += ' * DO NOT EDIT THIS FILE DIRECTLY - Edit files in src/js/ instead\n';
  output += ' * Run \'npm run build\' to regenerate this file\n';
  output += ' */\n\n';
  
  // ===== HERO SECTION =====
  output += '// ============================================================================\n';
  output += '// HERO SECTION ANIMATIONS\n';
  output += '// ============================================================================\n\n';
  
  let heroContent = fs.readFileSync(path.join(__dirname, 'src/js/hero-animations.js'), 'utf8');
  heroContent = cleanModuleCode(heroContent);
  
  // Extract the initHeroAnimations function body
  const initHeroMatch = heroContent.match(/function initHeroAnimations\(\) \{([\s\S]*?)\n\}/);
  let heroCode = heroContent.replace(/function initHeroAnimations\(\) \{[\s\S]*?\n\}/, '');
  
  // Remove the function declaration comment if it exists
  heroCode = heroCode.replace(/\*\*[\s\S]*?Initial hero animation on page load[\s\S]*?\*\//, '');
  heroCode = heroCode.replace(/^\/\s*$/, ''); // Remove stray slashes
  
  // Clean up any remaining empty lines or stray characters
  heroCode = heroCode.replace(/^\s*\/\s*$/gm, '');
  heroCode = heroCode.replace(/^\s*;\s*\}\s*$/gm, '');
  
  output += heroCode.trim() + '\n\n';
  
  // Add initHeroAnimations code inline
  if (initHeroMatch) {
    output += '// Initialize hero animations on page load\n';
    output += initHeroMatch[1].trim() + '\n\n';
  }
  
  // ===== RIPPLE EFFECT =====
  output += '// ============================================================================\n';
  output += '// RIPPLE EFFECT INITIALIZATION\n';
  output += '// ============================================================================\n\n';
  
  let rippleContent = fs.readFileSync(path.join(__dirname, 'src/js/ripple-effect.js'), 'utf8');
  rippleContent = cleanModuleCode(rippleContent);
  
  // Extract initRippleEffect function body
  const rippleMatch = rippleContent.match(/function initRippleEffect\(\) \{([\s\S]*?)\n\}/);
  if (rippleMatch) {
    // Get the function body content
    let rippleBody = rippleMatch[1];
    // Remove the function wrapper and keep just the body
    output += 'function initRippleEffect() {\n';
    output += rippleBody;
    output += '\n}\n\n';
  } else {
    // Fallback: if regex doesn't match, try to extract the content differently
    const altMatch = rippleContent.match(/\{([\s\S]*?)\n\}/);
    if (altMatch) {
      output += 'function initRippleEffect() {\n';
      output += altMatch[1];
      output += '\n}\n\n';
    }
  }
  
  // ===== MAIN GSAP SETUP =====
  output += '// ============================================================================\n';
  output += '// MAIN GSAP ANIMATIONS SETUP\n';
  output += '// ============================================================================\n\n';
  
  output += 'document.addEventListener("DOMContentLoaded", (event) => {\n';
  output += '  document.fonts.ready.then(() => {\n\n';
  output += '    // Register GSAP plugins\n';
  output += '    gsap.registerPlugin(ScrollTrigger, SplitText, Flip);\n\n';
  output += '    // Initial GSAP settings\n';
  output += '    gsap.set(".section_home-about", { position: "absolute" });\n';
  output += '    gsap.set(".section_home-service", { position: "absolute" });\n';
  output += '    gsap.set(".home_about-text, .service_border-text, .service_button", { autoAlpha: 0 });\n';
  output += '    gsap.set(".home_service-text", { autoAlpha: 0, y: 30, filter: "blur(8px)", scale: 0.85 });\n';
  output += '    gsap.set(".about_image-wrapper", { y: "100%" });\n';
  output += '    gsap.set(".about_design-wrapper", { x: "100%" });\n';
  output += '    gsap.set(".home_about-left", { clipPath: "polygon(0 0, 0 0, 0 100%, 0% 100%)" });\n\n';
  
  // ===== SERVICE SECTION =====
  output += '    // ========================================================================\n';
  output += '    // SERVICE SECTION ANIMATIONS\n';
  output += '    // ========================================================================\n\n';
  
  output += '    const serviceImages = document.querySelectorAll(".home_service-image");\n';
  output += '    const serviceTexts = document.querySelectorAll(".home_service-text");\n\n';
  output += '    gsap.set(serviceImages, { autoAlpha: 0, zIndex: 0 });\n\n';
  output += '    document.querySelectorAll(".service_button-wrapper").forEach(btn => {\n';
  output += '      gsap.set(btn, { autoAlpha: btn.getAttribute("data-text") == "1" ? 1 : 0 });\n';
  output += '    });\n\n';
  
  let serviceContent = fs.readFileSync(path.join(__dirname, 'src/js/service-reveal.js'), 'utf8');
  serviceContent = cleanModuleCode(serviceContent);
  
  // Split into lines and remove variable declarations
  let serviceLines = serviceContent.split('\n');
  let skipNextEmpty = false;
  let inVarBlock = false;
  let varBlockCount = 0;
  
  serviceLines = serviceLines.filter((line, index) => {
    const trimmed = line.trim();
    
    // Skip variable declarations
    if (trimmed.startsWith('let currentIndex') || 
        trimmed.startsWith('let isAnimating') || 
        trimmed.startsWith('let serviceRevealed') ||
        trimmed.startsWith('const clipHidden') ||
        trimmed.startsWith('const clipVisible')) {
      inVarBlock = true;
      varBlockCount++;
      return false;
    }
    
    // Skip empty line after variable block
    if (inVarBlock && trimmed === '' && varBlockCount >= 5) {
      inVarBlock = false;
      varBlockCount = 0;
      return false;
    }
    
    return true;
  });
  
  serviceContent = serviceLines.join('\n');
  
  // Modify function signatures to remove parameters
  serviceContent = serviceContent.replace(/function revealService\(index, serviceImages, serviceTexts\)/g, 'function revealService(index)');
  serviceContent = serviceContent.replace(/function resetServiceSection\(serviceImages, serviceTexts\)/g, 'function resetServiceSection()');
  serviceContent = serviceContent.replace(/function initServiceListeners\(serviceTexts, serviceImages\)/g, 'function initServiceListeners()');
  
  // Fix the revealService call in initServiceListeners
  serviceContent = serviceContent.replace(/revealService\(i, serviceImages, serviceTexts\)/g, 'revealService(i)');
  
  // Remove any leftover module.exports closing braces
  serviceContent = serviceContent.replace(/\n\/\/ Export functions for use in main file[\s\S]*?if \(typeof module !== 'undefined' && module\.exports\) \{[\s\S]*?\}\n?\}?\n?$/, '');
  
  // Add variable declarations inline
  output += '    let currentIndex = -1;\n';
  output += '    let isAnimating = false;\n';
  output += '    let serviceRevealed = false;\n\n';
  output += '    const clipHidden = "polygon(0 100%, 100% 100%, 100% 100%, 0 100%)";\n';
  output += '    const clipVisible = "polygon(0 100%, 100% 100%, 100% 0%, 0 0%)";\n\n';
  
  // Indent all lines, preserving empty lines
  serviceContent = serviceContent.split('\n').map(line => {
    if (line.trim() === '') return '';
    return '    ' + line;
  }).join('\n');
  
  // Remove any trailing module.exports remnants
  serviceContent = serviceContent.replace(/\s*\};\s*\}\s*$/, '');
  
  output += serviceContent + '\n\n';
  
  output += '    // Service text click handlers\n';
  output += '    initServiceListeners();\n\n';
  
  // ===== ABOUT SECTION =====
  output += '    // ========================================================================\n';
  output += '    // ABOUT SECTION ANIMATIONS\n';
  output += '    // ========================================================================\n\n';
  
  let aboutContent = fs.readFileSync(path.join(__dirname, 'src/js/about-section.js'), 'utf8');
  aboutContent = cleanModuleCode(aboutContent);
  
  // Remove initAboutSection function and call it inline
  aboutContent = aboutContent.replace(/function initAboutSection\(\) \{[\s\S]*?\n\}/, '');
  aboutContent = aboutContent.replace(/initAboutSection\(\);\n\n?/g, '');
  
  // Replace split initialization
  aboutContent = aboutContent.replace(/let split = null;/, 'const split = new SplitText(".home_about-text", { type: "lines", mask: "lines" });');
  
  // Remove getAboutLeftClip function (it's only used in scroll-timeline, not needed here)
  aboutContent = aboutContent.replace(/\/\*\*[\s\S]*?Gets the about left clip object[\s\S]*?\*\/\s*function getAboutLeftClip\(\) \{[\s\S]*?return aboutLeftClip;[\s\S]*?\}\s*/g, '');
  
  // Remove any leftover semicolons and closing braces from module.exports
  aboutContent = aboutContent.replace(/\s*;\s*\}\s*$/gm, '');
  
  // Indent all lines, preserving empty lines
  aboutContent = aboutContent.split('\n').map(line => {
    if (line.trim() === '') return '';
    return '    ' + line;
  }).join('\n');
  
  // Remove any trailing leftover braces after indentation
  aboutContent = aboutContent.replace(/\n\s*;\s*\n\s*\}\s*$/, '');
  
  output += aboutContent + '\n\n';
  
  // ===== LOGO ANIMATIONS =====
  output += '    // ========================================================================\n';
  output += '    // LOGO ANIMATIONS\n';
  output += '    // ========================================================================\n\n';
  
  let logoContent = fs.readFileSync(path.join(__dirname, 'src/js/logo-animations.js'), 'utf8');
  logoContent = cleanModuleCode(logoContent);
  
  // Extract initLogoAnimations function body
  const logoMatch = logoContent.match(/function initLogoAnimations\(\) \{([\s\S]*?)\n\}/);
  if (logoMatch) {
    let logoCode = logoMatch[1];
    // Indent all lines
    logoCode = logoCode.split('\n').map(line => '    ' + line).join('\n');
    output += logoCode + '\n\n';
  }
  
  // ===== SCROLL TIMELINE =====
  output += '    // ========================================================================\n';
  output += '    // MAIN SCROLL TIMELINE\n';
  output += '    // ========================================================================\n\n';
  
  let scrollContent = fs.readFileSync(path.join(__dirname, 'src/js/scroll-timeline.js'), 'utf8');
  scrollContent = cleanModuleCode(scrollContent);
  
  // Extract initScrollTimeline function body
  const scrollMatch = scrollContent.match(/function initScrollTimeline\([^)]+\) \{([\s\S]*?)\n\}/);
  if (scrollMatch) {
    let scrollCode = scrollMatch[1];
    
    // Replace function parameter calls with inline variables
    scrollCode = scrollCode.replace(/getAboutLeftClip\(\)/g, 'aboutLeftClip');
    scrollCode = scrollCode.replace(/getAboutRevealed\(\)/g, 'aboutRevealed');
    scrollCode = scrollCode.replace(/getAboutExiting\(\)/g, 'aboutExiting');
    scrollCode = scrollCode.replace(/getServiceRevealed\(\)/g, 'serviceRevealed');
    scrollCode = scrollCode.replace(/revealService\(0, serviceImages, serviceTexts\)/g, 'revealService(0)');
    scrollCode = scrollCode.replace(/resetServiceSection\(serviceImages, serviceTexts\)/g, 'resetServiceSection()');
    
    // Indent all lines
    scrollCode = scrollCode.split('\n').map(line => '    ' + line).join('\n');
    output += scrollCode + '\n\n';
  }
  
  // Initialize ripple
  output += '    // Initialize ripple effect\n';
  output += '    initRippleEffect();\n\n';
  
  // Close DOMContentLoaded
  output += '  });\n';
  output += '});\n';
  
  // Write the file
  fs.writeFileSync(outputFile, output, 'utf8');
  
  console.log('✓ Successfully built homepage_animations.js');
  console.log('✓ Ready to use!\n');
}

// Run the build
try {
  build();
} catch (error) {
  console.error('Build failed:', error.message);
  console.error(error.stack);
  process.exit(1);
}
