/**
 * Balnova Homepage Animations
 * Main animation file for homepage interactions
 * This file is auto-generated from src/js/ modules
 * DO NOT EDIT THIS FILE DIRECTLY - Edit files in src/js/ instead
 * Run 'npm run build' to regenerate this file
 */

// ============================================================================
// HERO SECTION ANIMATIONS
// ============================================================================

/**
 * Hero Section Animations
 * Handles letter and word reveal animations for the hero section
 */

let heroAnimated = false;

/**
 * Plays the hero reveal animation
 */
function playHeroReveal() {
  if (heroAnimated) return;
  heroAnimated = true;
  
  document.querySelectorAll('.hero-letter').forEach(function(el) {
    el.classList.add('animate');
  });
  
  setTimeout(function() {
    document.querySelectorAll('.hero-word').forEach(function(el) {
      el.classList.add('animate');
    });
  }, 800);
}

/**
 * Resets hero animations
 */
function resetHeroAnimations() {
  if (!heroAnimated) return;
  heroAnimated = false;
  
  document.querySelectorAll('.hero-letter').forEach(function(el) {
    el.classList.remove('animate');
  });
  
  document.querySelectorAll('.hero-word').forEach(function(el) {
    el.classList.remove('animate');
  });
}

// Initialize hero animations on page load
// Wait for DOM to be ready
(function initHeroOnLoad() {
  function initHeroAnimations() {
    const heroLetters = document.querySelectorAll('.hero-letter');
      const heroWords = document.querySelectorAll('.hero-word');
      
      if (heroLetters.length === 0 && heroWords.length === 0) {
        console.warn('Balnova Animations: Hero elements (.hero-letter, .hero-word) not found');
        return;
      }
      
      console.log('Balnova Animations: Hero elements found, initializing animations...');
      
      // Initial animation after page load
      setTimeout(function() {
        heroLetters.forEach(function(el) {
          el.classList.add('animate');
        });
        heroAnimated = true;
        console.log('Balnova Animations: Hero letters animated ✓');
      }, 4800);
    
      // Trigger subtitle words after logo letters finish
      setTimeout(function() {
        heroWords.forEach(function(el) {
          el.classList.add('animate');
        });
        console.log('Balnova Animations: Hero words animated ✓');
      }, 5600);
  }
  
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function() {
      setTimeout(initHeroAnimations, 100);
    });
  } else {
    setTimeout(initHeroAnimations, 100);
  }
})();

// ============================================================================
// RIPPLE EFFECT INITIALIZATION
// ============================================================================

function initRippleEffect() {
  // Check if jQuery and ripple plugin are loaded
  if (typeof $ === 'undefined' || typeof $.fn.ripples === 'undefined') {
    console.warn('Balnova Animations: jQuery or ripple plugin not loaded. Ripple effect will not work.');
    return;
  }
  
  const rippleElement = document.querySelector('#ripple');
  if (!rippleElement) {
    console.warn('Balnova Animations: #ripple element not found. Ripple effect will not work.');
    return;
  }


  const img = new Image();
  img.src = 'https://cdn.prod.website-files.com/6989b2816152e02c42b27db1/69946565ddabdcc627e1c8d7_image%20(1).webp';
  
  img.onload = () => {
    $('#ripple').ripples({
      resolution: 512,
      dropRadius: 15,
      perturbance: 0.0001,
    });
  };  
  img.onerror = () => {
    console.warn('Balnova Animations: Ripple image failed to load.');
  };
}

// ============================================================================
// MAIN GSAP ANIMATIONS SETUP
// ============================================================================

// Add startup message
console.log('Balnova Animations: Script loaded, waiting for DOM...');

// Function to check if GSAP and plugins are loaded
function checkGSAPDependencies() {
  if (typeof gsap === 'undefined') {
    console.error('Balnova Animations: GSAP is not loaded. Please include GSAP library.');
    return false;
  }
  if (typeof ScrollTrigger === 'undefined') {
    console.error('Balnova Animations: ScrollTrigger plugin is not loaded.');
    return false;
  }
  if (typeof SplitText === 'undefined') {
    console.error('Balnova Animations: SplitText plugin is not loaded.');
    return false;
  }
  if (typeof Flip === 'undefined') {
    console.error('Balnova Animations: Flip plugin is not loaded.');
    return false;
  }
  return true;
}

// Function to safely set GSAP properties
function safeGSAPSet(selector, props) {
  const elements = document.querySelectorAll(selector);
  if (elements.length === 0) {
    console.warn('Balnova Animations: Element not found:', selector);
    return false;
  }
  gsap.set(elements, props);
  return true;
}

document.addEventListener("DOMContentLoaded", (event) => {
  console.log('Balnova Animations: DOM loaded, waiting for fonts...');
  
  document.fonts.ready.then(() => {
    console.log('Balnova Animations: Fonts ready, initializing...');

    // Check if GSAP and plugins are loaded
    if (!checkGSAPDependencies()) {
      console.error('Balnova Animations: Required dependencies not loaded. Animations will not work.');
      console.error('Balnova Animations: Please include GSAP and plugins before this script.');
      return;
    }

    console.log('Balnova Animations: All dependencies loaded ✓');

    // Register GSAP plugins
    gsap.registerPlugin(ScrollTrigger, SplitText, Flip);
    console.log('Balnova Animations: GSAP plugins registered ✓');

    // Check for critical elements
    const mainWrapper = document.querySelector(".main-wrapper");
    if (!mainWrapper) {
      console.error('Balnova Animations: .main-wrapper element not found! This is required for scroll animations.');
      return;
    }
    console.log('Balnova Animations: .main-wrapper found ✓');

    // Initial GSAP settings - with element existence checks
    const aboutSection = safeGSAPSet(".section_home-about", { position: "absolute" });
    const serviceSection = safeGSAPSet(".section_home-service", { position: "absolute" });
    safeGSAPSet(".home_about-text, .service_border-text, .home_sevice-text, .service_button", { autoAlpha: 0 });
    safeGSAPSet(".js-service-text-disabled", { autoAlpha: 0, y: 30, filter: "blur(8px)", scale: 0.85 });
    safeGSAPSet(".about_image-wrapper", { y: "100%" });
    safeGSAPSet(".about_design-wrapper", { x: "100%" });
    
    // Check if .home_about-left exists before setting
    const aboutLeft = document.querySelector(".home_about-left");
    if (aboutLeft) {
      gsap.set(aboutLeft, { clipPath: "polygon(0 0, 0 0, 0 100%, 0% 100%)" });
      console.log('Balnova Animations: .home_about-left found and initialized ✓');
    } else {
      console.warn('Balnova Animations: .home_about-left element not found');
    }
    
    if (!aboutSection) {
      console.warn('Balnova Animations: .section_home-about not found - about section animations may not work');
    }
    if (!serviceSection) {
      console.warn('Balnova Animations: .section_home-service not found - service section animations may not work');
    }

    // ========================================================================
    // SERVICE SECTION ANIMATIONS
    // ========================================================================

    // Horizontal process scroll for service text on further scroll
    function serviceProcessScroll() {
      try {
        if (typeof isMobile === "function" && isMobile()) return;
      } catch (e) {
        // If isMobile doesn't exist, ignore and continue
      }

      
      const processWrapper = document.querySelector(".service_text-container");
      if (!processWrapper) return;

      const maxX = -(processWrapper.offsetWidth - 1248);
      if (!isFinite(maxX) || maxX >= 0) return;

      gsap.timeline({
        scrollTrigger: {
          trigger: ".section_home-service",
          start: "center center",
          end: "+=1500",
          scrub: true,
          pin: true,
          anticipatePin: 1
        },
        defaults: { ease: "none" }
      }).fromTo(
        processWrapper,
        { x: 0 },
        { x: maxX }
      );
    }

    const serviceImages = document.querySelectorAll(".js-service-image-disabled");
    const serviceTexts = document.querySelectorAll(".js-service-text-disabled");
    const homeServiceTexts = document.querySelectorAll(".home_sevice-text");

    gsap.set(serviceImages, { autoAlpha: 0, zIndex: 0 });

    document.querySelectorAll(".js-service-button-wrapper-disabled").forEach(btn => {
      gsap.set(btn, { autoAlpha: btn.getAttribute("data-text") == "1" ? 1 : 0 });
    });

    let currentIndex = -1;
    let isAnimating = false;
    let serviceRevealed = false;

    // Initialize horizontal process scroll for service section
    serviceProcessScroll();

    const clipHidden = "polygon(0 100%, 100% 100%, 100% 100%, 0 100%)";
    const clipVisible = "polygon(0 100%, 100% 100%, 100% 0%, 0 0%)";

    /**
     * Service Section Animations
     * Handles service image reveal and text interactions
     */


    /**
     * Reveals a service by index
     * @param {number} index - The service index to reveal
     * @param {NodeList} serviceImages - All service image elements
     * @param {NodeList} serviceTexts - All service text elements
     */
    function revealService(index) {
      if (isAnimating) return;
      isAnimating = true;

      // First reveal - show all service elements
      if (!serviceRevealed) {
        serviceRevealed = true;

        // Reset position in case they were animated off to the right previously
        gsap.set(".home_sevice-text, .service_button", { x: 0 });

        // Only show up to 3 service text items at a time
        if (homeServiceTexts && homeServiceTexts.length > 0) {
          homeServiceTexts.forEach((el, i) => {
            if (i < 3) {
              gsap.to(el, {
                autoAlpha: 1,
                duration: 0.5,
                ease: "none",
                overwrite: true
              });
            } else {
              gsap.set(el, { autoAlpha: 0 });
            }
          });
        } else {
          gsap.to(".home_sevice-text", {
            autoAlpha: 1, 
            duration: 0.5, 
            ease: "none", 
            overwrite: true
          });
        }
        gsap.to(".service_button", {
          autoAlpha: 1,
          y: 0,
          filter: "blur(0px)",
          scale: 1,
          duration: 0.7,
          ease: "power3.out",
          stagger: 0.25,
          overwrite: true
        });
      }

      // Update active text
      serviceTexts.forEach((t, i) => {
        t.classList.toggle("active", i === index);
      });

      // Update button visibility
      document.querySelectorAll(".service_button-wrapper").forEach(btn => {
        gsap.to(btn, {
          autoAlpha: btn.getAttribute("data-text") == index + 1 ? 1 : 0,
          duration: 0.5
        });
      });

      // First service reveal
      if (currentIndex === -1) {
        gsap.set(serviceImages[index], {
          visibility: "visible",
          opacity: 1,
          zIndex: 1,
          clipPath: clipHidden
        });

        gsap.to(serviceImages[index], {
          clipPath: clipVisible,
          duration: 1,
          ease: "power2.out",
          onComplete: () => {
            currentIndex = index;
            isAnimating = false;
          }
        });
        return;
      }

      // Subsequent reveals - handle transitions
      const isNext = index > currentIndex;
      const prevIndex = currentIndex;

      if (isNext) {
        // Moving forward
        gsap.set(serviceImages[index], {
          visibility: "visible",
          opacity: 1,
          zIndex: 2,
          clipPath: clipHidden
        });
        gsap.set(serviceImages[prevIndex], { zIndex: 1 });

        gsap.to(serviceImages[index], {
          clipPath: clipVisible,
          duration: 1,
          ease: "power2.out",
          onComplete: () => {
            gsap.set(serviceImages[prevIndex], { autoAlpha: 0, zIndex: 0, clipPath: "none" });
            gsap.set(serviceImages[index], { zIndex: 1 });
            currentIndex = index;
            isAnimating = false;
          }
        });
      } else {
        // Moving backward
        gsap.set(serviceImages[index], {
          visibility: "visible",
          opacity: 1,
          zIndex: 1,
          clipPath: clipVisible
        });
        gsap.set(serviceImages[prevIndex], { zIndex: 2 });

        gsap.to(serviceImages[prevIndex], {
          clipPath: clipHidden,
          duration: 1,
          ease: "power2.out",
          onComplete: () => {
            gsap.set(serviceImages[prevIndex], { autoAlpha: 0, zIndex: 0, clipPath: "none" });
            gsap.set(serviceImages[index], { zIndex: 1 });
            currentIndex = index;
            isAnimating = false;
          }
        });
      }
    }

    /**
     * Resets service section to initial state
     * @param {NodeList} serviceImages - All service image elements
     * @param {NodeList} serviceTexts - All service text elements
     */
    function resetServiceSection() {
      if (isAnimating) {
        gsap.killTweensOf(serviceImages);
        gsap.killTweensOf(".service_border-text, .service_button");
        gsap.killTweensOf(".home_sevice-text, .service_button");
      }

      serviceImages.forEach(img => {
        gsap.set(img, { autoAlpha: 0, zIndex: 0, clipPath: "none" });
      });

      gsap.set(".service_border-text", { autoAlpha: 0, overwrite: true });
      // When leaving the service section (scrolling up), slide text/buttons to the right and hide
      gsap.to(".home_sevice-text, .service_button", { 
        autoAlpha: 0,
        x: 100,
        duration: 0.5,
        ease: "power3.in",
        overwrite: true
      });
      serviceTexts.forEach(t => t.classList.remove("active"));
      gsap.set(".js-service-text-disabled", { 
        autoAlpha: 0, 
        y: 30, 
        filter: "blur(8px)", 
        scale: 0.85, 
        overwrite: true 
      });

      document.querySelectorAll(".js-service-button-wrapper-disabled").forEach(btn => {
        gsap.set(btn, { autoAlpha: btn.getAttribute("data-text") == "1" ? 1 : 0 });
      });

      currentIndex = -1;
      serviceRevealed = false;
      isAnimating = false;

      
    }

    /**
     * Initializes service section event listeners
     * @param {NodeList} serviceTexts - All service text elements
     * @param {NodeList} serviceImages - All service image elements
     */
    function initServiceListeners() {
      serviceTexts.forEach((text, i) => {
        text.addEventListener("click", () => {
          if (isAnimating || currentIndex === i) return;
          revealService(i);
        });
      });
    }

    // Service text click handlers
    initServiceListeners();

    // ========================================================================
    // ABOUT SECTION ANIMATIONS
    // ========================================================================

    /**
     * About Section Animations
     * Handles about section reveal and exit animations
     */

    let aboutLeftClip = { x2: 30, x4: 76 };
    let textAnimated = false;
    let aboutRevealed = false;
    let aboutExiting = false;
    let aboutClipTl = null;
    let split = null;
        const aboutTextEl = document.querySelector(".home_about-text");
        if (aboutTextEl && typeof SplitText !== 'undefined') {
          split = new SplitText(".home_about-text", { type: "words", mask: "lines" });
        } else {
          console.warn('Balnova Animations: .home_about-text element or SplitText plugin not found');
        }


    /**
     * Initializes the about section
     */


    /**
     * Plays the about section reveal animation
     */
    function playAboutReveal() {
      if (aboutRevealed) return;
      aboutRevealed = true;
      aboutExiting = false;

      aboutLeftClip.x2 = 0;
      aboutLeftClip.x4 = 0;

      aboutClipTl = gsap.timeline();

      aboutClipTl.to(aboutLeftClip, {
        x2: 30, 
        x4: 76, 
        duration: 2, 
        ease: "power2.out",
        onUpdate: () => {
          const aboutLeftEl = document.querySelector(".home_about-left");
          if (aboutLeftEl) {
            aboutLeftEl.style.clipPath = 
              `polygon(0 0, ${aboutLeftClip.x2}% 0, ${aboutLeftClip.x4}% 100%, 0 100%)`;
          }
        },
        onComplete: () => {
          if (textAnimated) return;
          textAnimated = true;
          gsap.fromTo(".home_about-content", { scale: 0.8 }, { scale: 1, duration: 2, ease: "power2.out" });
          gsap.set(".home_about-content", { opacity: 1 });
          gsap.set(".home_about-text", { autoAlpha: 1 });
          if (split && split.words) {
            gsap.from(split.words, { 
              opacity: 0,
              duration: 2,
              ease: "sine.out",
              stagger: 0.1,
            });
          }
          gsap.to(".about_image-wrapper", { 
            y: "0%", 
            duration: 1.5, 
            ease: "power1.out", 
            stagger: 0.25,
          });
          gsap.to(".about_design-wrapper", { x: "0%", duration: 1.5, ease: "power1.out" });
          gsap.set(".home_about-left", { 
            clipPath: "polygon(0px 0px, 30% 0px, 76% 100%, 0px 100%)" 
          });
        }
      });
    }

    /**
     * Plays the about section exit animation
     */
    function playAboutExit() {
      if (aboutExiting || !aboutRevealed) return;
      aboutExiting = true;

      const exitTl = gsap.timeline({
        onComplete: () => {
          aboutRevealed = false;
          textAnimated = false;
          aboutExiting = false;

          gsap.set(".home_about-text", { autoAlpha: 0, x: "0%" });
          gsap.set(".about_image-wrapper", { y: "100%" });
          gsap.set(".about_design-wrapper", { x: "100%" });
          gsap.set(".home_about-left", { 
            clipPath: "polygon(0 0, 0 0, 0 100%, 0% 100%)" 
          });

          aboutLeftClip.x2 = 30;
          aboutLeftClip.x4 = 76;
        }
      });

      exitTl
        .to(".home_about-text", { x: "0%", duration: 0.8, ease: "power3.in" })
        .to(".about_image-wrapper", { y: "100%", duration: 0.8, ease: "power3.in" }, "<")
        .to(".about_design-wrapper", { x: "100%", duration: 0.8, ease: "power3.in" }, "<")
        .add(() => {
          if (aboutClipTl) {
            aboutClipTl.reverse();
          }
        }, "<");
    }

    /**
     * Gets the about left clip object for timeline updates
     */
    function getAboutLeftClip() {
      return aboutLeftClip;
    }

    // ========================================================================
    // LOGO ANIMATIONS
    // ========================================================================
    
      // State for logo flip animation
      let logoFlipped = false;
      let logoAnimating = false;
    
      const logoLink = document.querySelector(".header_logo-link");
      const mainLogo = document.querySelector(".main_logo");
      const logoSvg = document.querySelector(".logo_svg");
    
      ScrollTrigger.create({
        trigger: ".main-wrapper",
        start: "top top",
        end: "+=1800",
        onUpdate: (self) => {
          // Flip logo when scrolling down
          if (self.progress > 0.05 && !logoFlipped) {
            logoFlipped = true;
            if (logoAnimating) {
              gsap.killTweensOf(mainLogo);
              gsap.killTweensOf(logoSvg);
            }
            logoAnimating = true;
            const state = Flip.getState(logoSvg);
            gsap.to(mainLogo, {
              opacity: 0,
              width: 0,
              duration: 1,
              ease: "power3.out",
              transformOrigin: "right right",
            });
            logoLink.style.justifyContent = "center";
            Flip.from(state, {
              duration: 1,
              ease: "power3.out",
              onComplete: () => { logoAnimating = false; }
            });
          }
    
          // Unflip logo when scrolling back up
          if (self.progress < 0.05 && logoFlipped) {
            logoFlipped = false;
            if (logoAnimating) {
              gsap.killTweensOf(mainLogo);
              gsap.killTweensOf(logoSvg);
            }
            logoAnimating = true;
            const state = Flip.getState(logoSvg);
            gsap.to(mainLogo, {
              opacity: 1,
              width: "auto",
              duration: 1,
              ease: "power3.out",
              transformOrigin: "right right"
            });
            logoLink.style.justifyContent = "";
            Flip.from(state, {
              duration: 1,
              ease: "power3.out",
              onComplete: () => { logoAnimating = false; }
            });
          }
        }
      });

    // ========================================================================
    // MAIN SCROLL TIMELINE
    // ========================================================================

    
      let prevProgress = 0;
      let heroCleared = false;
    
      const mainTimeline = gsap.timeline({
        scrollTrigger: {
          trigger: ".main-wrapper",
          start: "top top",
          end: "+=1000",
          scrub: 1,
          pin: true,
          onUpdate: (self) => {
            const scrollingUp = self.progress < prevProgress;
    
            // Handle hero animations
            if (!scrollingUp && self.progress > 0.3 && !heroCleared) {
              heroCleared = true;
              resetHeroAnimations();
            }
    
            if (scrollingUp && self.progress < 0.05 && heroCleared) {
              heroCleared = false;
              playHeroReveal();
            }
    
            // Handle about section
            if (self.progress > 0.15 && !aboutRevealed && !aboutExiting) {
              playAboutReveal();
            }
    
            if (scrollingUp && self.progress < 0.15 && aboutRevealed && !aboutExiting) {
              playAboutExit();
            }
    
            // Handle service section
            if (self.progress > 0.99 && !serviceRevealed) {
              revealService(0);
            }

            // While scrolling up near the bottom of the main wrapper,
            // slide the service text and button to the right
            if (scrollingUp && serviceRevealed && self.progress <= 0.99 && self.progress >= 0.8) {
              const xVal = gsap.utils.mapRange(1, 0.8, 0, 120, self.progress);
              gsap.to(".home_sevice-text, .service_button", {
                x: xVal,
                duration: 0.1,
                ease: "none",
                overwrite: true
              });
            }

            if (self.progress < 0.8 && serviceRevealed) {
              resetServiceSection();
            }

            prevProgress = self.progress;
          }
        }
      })
      .fromTo(".section_hero",
        { clipPath: "polygon(0 0, 100% 0, 100% 100%, 0 100%)" },
        { clipPath: "polygon(0 0, 100% 0, 100% 0%, 0 0%)", ease: "none" },
        0)
      .to(".section_home-about", { y: 0, ease: "none" }, 0)
      .to({}, { duration: 1 })
      .to(".home_about-text", { x: "100%", ease: "power3.in" })
      .to(".about_image-wrapper", { opacity: 0, ease: "power3.in" }, "<")
      .to(".about_design-wrapper", { opacity: 0, ease: "power3.in" }, "<")
      .to(aboutLeftClip, {
        x2: 100, 
        x4: 100, 
        ease: "none",
        onUpdate: () => {
          const aboutLeftEl = document.querySelector(".home_about-left");
          if (aboutLeftEl) {
            aboutLeftEl.style.clipPath = 
              `polygon(0 0, ${aboutLeftClip.x2}% 0, ${aboutLeftClip.x4}% 100%, 0 100%)`;
          }
        }
      })
      .to(".home_about-left", { "--grad-angle": "-10deg", ease: "none" }, "<");
    
      // Background position animations
      mainTimeline
        .fromTo(".section_hero",
          { backgroundPositionY: "0px" },
          { backgroundPositionY: "-50px", ease: "none" },
          0)
        .fromTo(".section_home-about",
          { backgroundPositionY: "0px" },
          { backgroundPositionY: "-50px", ease: "none" },
          0);

    // Initialize ripple effect
    initRippleEffect();
    
    // Final initialization message
    console.log('Balnova Animations: Initialization complete! ✓');
    console.log('Balnova Animations: If animations are not working, check:');
    console.log('  1. All required HTML classes exist');
    console.log('  2. CSS file is loaded');
    console.log('  3. GSAP and plugins are loaded before this script');

  });
});