/**
 * Balnova Homepage Animations
 * Main animation file for homepage interactions
 * This file is auto-generated from src/js/ modules
 * DO NOT EDIT THIS FILE DIRECTLY - Edit files in src/js/ instead
 * Run 'npm run build' to regenerate this file
 */

// ============================================================================
// HERO SECTION ANIMATIONS
// ============================================================================

let heroAnimated = false;

function playHeroReveal() {
  if (heroAnimated) return;
  heroAnimated = true;
  
  document.querySelectorAll('.hero-letter').forEach(function(el) {
    el.classList.add('animate');
  });
  
  setTimeout(function() {
    document.querySelectorAll('.hero-word').forEach(function(el) {
      el.classList.add('animate');
    });
  }, 800);
}

function resetHeroAnimations() {
  if (!heroAnimated) return;
  heroAnimated = false;
  
  document.querySelectorAll('.hero-letter').forEach(function(el) {
    el.classList.remove('animate');
  });
  
  document.querySelectorAll('.hero-word').forEach(function(el) {
    el.classList.remove('animate');
  });
}

(function initHeroOnLoad() {
  function initHeroAnimations() {
    const heroLetters = document.querySelectorAll('.hero-letter');
      const heroWords = document.querySelectorAll('.hero-word');
      
      if (heroLetters.length === 0 && heroWords.length === 0) {
        console.warn('Balnova Animations: Hero elements (.hero-letter, .hero-word) not found');
        return;
      }
      
      console.log('Balnova Animations: Hero elements found, initializing animations...');
      
      setTimeout(function() {
        heroLetters.forEach(function(el) {
          el.classList.add('animate');
        });
        heroAnimated = true;
        console.log('Balnova Animations: Hero letters animated ✓');
      }, 4800);
    
      setTimeout(function() {
        heroWords.forEach(function(el) {
          el.classList.add('animate');
        });
        console.log('Balnova Animations: Hero words animated ✓');
      }, 5600);
  }
  
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function() {
      setTimeout(initHeroAnimations, 100);
    });
  } else {
    setTimeout(initHeroAnimations, 100);
  }
})();

// ============================================================================
// RIPPLE EFFECT INITIALIZATION
// ============================================================================

function initRippleEffect() {
  if (typeof $ === 'undefined' || typeof $.fn.ripples === 'undefined') {
    console.warn('Balnova Animations: jQuery or ripple plugin not loaded. Ripple effect will not work.');
    return;
  }
  
  const rippleElement = document.querySelector('#ripple');
  if (!rippleElement) {
    console.warn('Balnova Animations: #ripple element not found. Ripple effect will not work.');
    return;
  }

  const img = new Image();
  img.src = 'https://cdn.prod.website-files.com/6989b2816152e02c42b27db1/69946565ddabdcc627e1c8d7_image%20(1).webp';
  
  img.onload = () => {
    $('#ripple').ripples({
      resolution: 512,
      dropRadius: 15,
      perturbance: 0.0001,
    });
  };  
  img.onerror = () => {
    console.warn('Balnova Animations: Ripple image failed to load.');
  };
}

// ============================================================================
// MAIN GSAP ANIMATIONS SETUP
// ============================================================================

console.log('Balnova Animations: Script loaded, waiting for DOM...');

function checkGSAPDependencies() {
  if (typeof gsap === 'undefined') {
    console.error('Balnova Animations: GSAP is not loaded. Please include GSAP library.');
    return false;
  }
  if (typeof ScrollTrigger === 'undefined') {
    console.error('Balnova Animations: ScrollTrigger plugin is not loaded.');
    return false;
  }
  if (typeof SplitText === 'undefined') {
    console.error('Balnova Animations: SplitText plugin is not loaded.');
    return false;
  }
  if (typeof Flip === 'undefined') {
    console.error('Balnova Animations: Flip plugin is not loaded.');
    return false;
  }
  return true;
}

function safeGSAPSet(selector, props) {
  const elements = document.querySelectorAll(selector);
  if (elements.length === 0) {
    console.warn('Balnova Animations: Element not found:', selector);
    return false;
  }
  gsap.set(elements, props);
  return true;
}

document.addEventListener("DOMContentLoaded", (event) => {
  console.log('Balnova Animations: DOM loaded, waiting for fonts...');
  
  document.fonts.ready.then(() => {
    console.log('Balnova Animations: Fonts ready, initializing...');

    if (!checkGSAPDependencies()) {
      console.error('Balnova Animations: Required dependencies not loaded. Animations will not work.');
      console.error('Balnova Animations: Please include GSAP and plugins before this script.');
      return;
    }

    console.log('Balnova Animations: All dependencies loaded ✓');

    gsap.registerPlugin(ScrollTrigger, SplitText, Flip);
    console.log('Balnova Animations: GSAP plugins registered ✓');

    const mainWrapper = document.querySelector(".main-wrapper");
    if (!mainWrapper) {
      console.error('Balnova Animations: .main-wrapper element not found! This is required for scroll animations.');
      return;
    }
    console.log('Balnova Animations: .main-wrapper found ✓');

    const aboutSection = safeGSAPSet(".section_home-about", { position: "absolute" });
    const serviceSection = safeGSAPSet(".section_home-service", { position: "absolute" });
    safeGSAPSet(".home_about-text", { autoAlpha: 0 });
    safeGSAPSet(".about_image-wrapper", { y: "100%" });
    safeGSAPSet(".about_design-wrapper", { x: "100%" });
    
    const aboutLeft = document.querySelector(".home_about-left");
    if (aboutLeft) {
      gsap.set(aboutLeft, { clipPath: "polygon(0 0, 0 0, 0 100%, 0% 100%)" });
      console.log('Balnova Animations: .home_about-left found and initialized ✓');
    } else {
      console.warn('Balnova Animations: .home_about-left element not found');
    }
    
    if (!aboutSection) {
      console.warn('Balnova Animations: .section_home-about not found - about section animations may not work');
    }
    if (!serviceSection) {
      console.warn('Balnova Animations: .section_home-service not found - service section animations may not work');
    }

    // ========================================================================
    // ABOUT SECTION ANIMATIONS
    // ========================================================================

    let aboutLeftClip = { x2: 30, x4: 76 };
    let textAnimated = false;
    let aboutRevealed = false;
    let aboutExiting = false;
    let aboutClipTl = null;
    let split = null;
        const aboutTextEl = document.querySelector(".home_about-text");
        if (aboutTextEl && typeof SplitText !== 'undefined') {
          split = new SplitText(".home_about-text", { type: "words", mask: "lines" });
        } else {
          console.warn('Balnova Animations: .home_about-text element or SplitText plugin not found');
        }

    function playAboutReveal() {
      if (aboutRevealed) return;
      aboutRevealed = true;
      aboutExiting = false;

      aboutLeftClip.x2 = 0;
      aboutLeftClip.x4 = 0;

      aboutClipTl = gsap.timeline();

      aboutClipTl.to(aboutLeftClip, {
        x2: 30, 
        x4: 76, 
        duration: 2, 
        ease: "power2.out",
        onUpdate: () => {
          const aboutLeftEl = document.querySelector(".home_about-left");
          if (aboutLeftEl) {
            aboutLeftEl.style.clipPath = 
              `polygon(0 0, ${aboutLeftClip.x2}% 0, ${aboutLeftClip.x4}% 100%, 0 100%)`;
          }
        },
        onComplete: () => {
          if (textAnimated) return;
          textAnimated = true;
          gsap.fromTo(".home_about-content", { scale: 0.8 }, { scale: 1, duration: 4, ease: "none" });
          gsap.set(".home_about-content", { opacity: 1 });
          gsap.set(".home_about-text", { autoAlpha: 1 });
          if (split && split.words) {
            gsap.from(split.words, { 
              opacity: 0,
              duration: 2,
              ease: "sine.out",
              stagger: 0.1,
            });
          }
          gsap.to(".about_image-wrapper", { 
            y: "0%", 
            duration: 1.5, 
            ease: "power1.out", 
            stagger: 0.25,
          });
          gsap.to(".about_design-wrapper", { x: "0%", duration: 1.5, ease: "power1.out" });
          gsap.set(".home_about-left", { 
            clipPath: "polygon(0px 0px, 30% 0px, 76% 100%, 0px 100%)" 
          });
        }
      });
    }

    function playAboutExit() {
      if (aboutExiting || !aboutRevealed) return;
      aboutExiting = true;

      const exitTl = gsap.timeline({
        onComplete: () => {
          aboutRevealed = false;
          textAnimated = false;
          aboutExiting = false;

          gsap.set(".home_about-text", { autoAlpha: 0, x: "0%" });
          gsap.set(".about_image-wrapper", { y: "100%" });
          gsap.set(".about_design-wrapper", { x: "100%" });
          gsap.set(".home_about-left", { 
            clipPath: "polygon(0 0, 0 0, 0 100%, 0% 100%)" 
          });

          aboutLeftClip.x2 = 30;
          aboutLeftClip.x4 = 76;
        }
      });

      exitTl
        .to(".home_about-text", { x: "0%", duration: 0.8, ease: "power3.in" })
        .to(".about_image-wrapper", { y: "100%", duration: 0.8, ease: "power3.in" }, "<")
        .to(".about_design-wrapper", { x: "100%", duration: 0.8, ease: "power3.in" }, "<")
        .add(() => {
          if (aboutClipTl) {
            aboutClipTl.reverse();
          }
        }, "<");
    }

    function getAboutLeftClip() {
      return aboutLeftClip;
    }

    // ========================================================================
    // LOGO ANIMATIONS
    // ========================================================================
    
      let logoFlipped = false;
      let logoAnimating = false;
    
      const logoLink = document.querySelector(".header_logo-link");
      const mainLogo = document.querySelector(".main_logo");
      const logoSvg = document.querySelector(".logo_svg");
    
      ScrollTrigger.create({
        trigger: ".main-wrapper",
        start: "top top",
        end: "+=1800",
        onUpdate: (self) => {
          if (self.progress > 0.05 && !logoFlipped) {
            logoFlipped = true;
            if (logoAnimating) {
              gsap.killTweensOf(mainLogo);
              gsap.killTweensOf(logoSvg);
            }
            logoAnimating = true;
            const state = Flip.getState(logoSvg);
            gsap.to(mainLogo, {
              opacity: 0,
              width: 0,
              duration: 1,
              ease: "power3.out",
              transformOrigin: "right right",
            });
            logoLink.style.justifyContent = "center";
            Flip.from(state, {
              duration: 1,
              ease: "power3.out",
              onComplete: () => { logoAnimating = false; }
            });
          }
    
          if (self.progress < 0.05 && logoFlipped) {
            logoFlipped = false;
            if (logoAnimating) {
              gsap.killTweensOf(mainLogo);
              gsap.killTweensOf(logoSvg);
            }
            logoAnimating = true;
            const state = Flip.getState(logoSvg);
            gsap.to(mainLogo, {
              opacity: 1,
              width: "auto",
              duration: 1,
              ease: "power3.out",
              transformOrigin: "right right"
            });
            logoLink.style.justifyContent = "";
            Flip.from(state, {
              duration: 1,
              ease: "power3.out",
              onComplete: () => { logoAnimating = false; }
            });
          }
        }
      });

    // ========================================================================
    // MAIN SCROLL TIMELINE
    // ========================================================================

    
      let prevProgress = 0;
      let heroCleared = false;
    
      const mainTimeline = gsap.timeline({
        scrollTrigger: {
          trigger: ".main-wrapper",
          start: "top top",
          end: "+=1000",
          scrub: 1,
          pin: true,
          onUpdate: (self) => {
            const scrollingUp = self.progress < prevProgress;
    
            if (!scrollingUp && self.progress > 0.3 && !heroCleared) {
              heroCleared = true;
              resetHeroAnimations();
            }
    
            if (scrollingUp && self.progress < 0.05 && heroCleared) {
              heroCleared = false;
              playHeroReveal();
            }
    
            if (self.progress > 0.15 && !aboutRevealed && !aboutExiting) {
              playAboutReveal();
            }
    
            if (scrollingUp && self.progress < 0.15 && aboutRevealed && !aboutExiting) {
              playAboutExit();
            }
    
            prevProgress = self.progress;
          }
        }
      })
      .fromTo(".section_hero",
        { clipPath: "polygon(0 0, 100% 0, 100% 100%, 0 100%)" },
        { clipPath: "polygon(0 0, 100% 0, 100% 0%, 0 0%)", ease: "none" },
        0)
      .to(".section_home-about", { y: 0, ease: "none" }, 0)
      .to({}, { duration: 1 })
      .to(".home_about-text", { x: "100%", ease: "power3.in" })
      .to(".about_image-wrapper", { opacity: 0, ease: "power3.in" }, "<")
      .to(".about_design-wrapper", { opacity: 0, ease: "power3.in" }, "<")
      .to(aboutLeftClip, {
        x2: 100, 
        x4: 100, 
        ease: "none",
        onUpdate: () => {
          const aboutLeftEl = document.querySelector(".home_about-left");
          if (aboutLeftEl) {
            aboutLeftEl.style.clipPath = 
              `polygon(0 0, ${aboutLeftClip.x2}% 0, ${aboutLeftClip.x4}% 100%, 0 100%)`;
          }
        }
      })
      .to(".home_about-left", { "--grad-angle": "-10deg", ease: "none" }, "<");
    
      mainTimeline
        .fromTo(".section_hero",
          { backgroundPositionY: "0px" },
          { backgroundPositionY: "-50px", ease: "none" },
          0)
        .fromTo(".section_home-about",
          { backgroundPositionY: "0px" },
          { backgroundPositionY: "-50px", ease: "none" },
          0);

    initRippleEffect();
    
    console.log('Balnova Animations: Initialization complete! ✓');
    console.log('Balnova Animations: If animations are not working, check:');
    console.log('  1. All required HTML classes exist');
    console.log('  2. CSS file is loaded');
    console.log('  3. GSAP and plugins are loaded before this script');

  });
});